### ISSUE TITLE
REQ HELP: AI A2A Dispatcher

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/OPAR#1]
Would it be possible to setup a script to achieve the following effect:

**1. Combat Air Patrol (CAP):**
Have 1 CAP per squadron (or airfield) up flying a CAP pattern on a zone (trigger zone) in the .miz. This need to be changed easily in the .miz without changes in the script file.
If possible, customizable based on amount of squadrons on a base.

Details: 
- CAP's fly in a racetrack pattern, hotleg toward Blue airfields/FLOT. ( So a AWACS controller is able to see that it is a CAP)
- For randomness, at times aircraft can fly with radar off, and turn on radar when they leave CAP orbit to intercept (when they have recived an order from AWACS or GCI).
- Normally a CAP will be flown by a 2ship. However, for randomness, make a small chance for it to be a 4ship (and if possible, have 2 ac fly to do AAR, while 2 stay at the CAP racetrack when they need to refuel). Also connected to readiness state further down (If squadron is set to high readiness, high chance for a 4-ship, if low readiness no chance for 4ship)
- Very similar to what is currently implemented in OPUF

**2. Quick Reaction Alert (QRA):**
Primary airfields have QRA fighters aswell as CAP flights. This will be a seperare squadron from the CAP squadron. These aircraft are by default on a 15 minute alert (15 minutes from they are given a task until they are airborne). For randomness (put this between 7 minutes and 25 minutes). If a CAP is tasked, the QRA flights from one of the airfields will be launched (closest one?). The other is a backup, so if the original CAP flight is shot down, or the QRA flight is shot down, the second QRA flight is launched.
NOTE: Called GCI in the Moose AI A2A dispatcher description

3. Readiness state 
If possible, have a way of setting the availability of the aircrafts based on readiness state:
![bilde](https://user-images.githubusercontent.com/26002570/81397623-019ce400-9128-11ea-9713-1d76a3d4f738.png)
This gives the amount of aircrafts that is availeble for the squadron for CAP and QRA missions. With high readiness between 8-10 aircrafts is availeble, with normal readiness 5-8 aircraft are availeble, with low readiness 2-6 aircraft are availeble. 

**4. AWACS**
The script (or a different script) also handles the enemys AWACS.
Same as CAP, AWACS uses a zone and establish a racetrack pattern and are tied into the detection of incoming aircraft. If no AWACS is airborne, only EWR on the ground will

**5. AAR**
Similar to AWACS, a tanker squadron will setup a tanker refueling track based on a trigger zone set in the .miz. The airborne CAP aircrafts will then refuel with the tanker when they are low on fuel (below 50% and not beeing tasked with anything). This to keep CAPs airborne longer.

**6. Russian Carrier**
A russian carrier will also be deployed in the Gulf. And this should be connected with a squadron beeing able to do CAP as any other, but also have a QRA on 5 minute alert, launcing against any incoming aircraft either at a distance from the carrier, or a within a triggerzone, or a border (similar to a cold border).

**7. Forward staging**
On airfields with no squadrons there is a 50% chance that the airfield will have a 2ship forward staged. If it is forwardstaged it will have on a 15 minute alert to respond to any threats (QRA/GCI). For randomness, set time between 7 and 25 minutes. This is an effort to spread forces and not keeping all flights at the main airbases.

**Tied to IADS**
Skynet IADS will be used to handle a IADS.
It would be very desirable to tie the detection by the IADS to the trigger/detection of the AI A2A dispatcher. (Launch of QRA/GCI flights), or triggering of CAPs to start an intercept. This will specially be useful in the missions where no AWACS is availeble.
It looks like the author of the script is considering this, see screenshot below (from his backlog on the Skynet github page):
![bilde](https://user-images.githubusercontent.com/26002570/81498996-6e4ee480-92c8-11ea-97f0-57a4ab9dc0b5.png)
![bilde](https://user-images.githubusercontent.com/26002570/81511782-00340d00-931c-11ea-829d-fbdd5f27ecdd.png)

Link to Skynet IADS: https://github.com/walder/Skynet-IADS
Skynet IADS Discord: https://discord.gg/GdsDf8x

**Objectives / Purpose of this script**
1. The primary objective or purpose for this script is to protect the defended airspace
2. Secondary objective is to prevent any interference with AWACS or  Tanker activity 
    Both AWACS and Tanker's are High Value Units so something the enemy can not afford to loose.
3. Third, the effect is to prevent any Blue air activity over enemy controlled territory, preventing BLUE from conducting CAS, AR, SEAD or Strike missions
4. Protect the red carrier group operating at sea.
5. Having the Air opposition beeing handled dynamicly, making it possible for the event host to fly and not know what will happen, but also keeping it in line with the current intelligence availeble.

**Other details**
- The script should use the cold border logic from Moose AI A2A dispacther. This to make it possible for the mission designer to create CAS taskings or AR taskings that will not be effected by the script, and thus making it possible for A-10 and KA-50 to do operations in certain areas when the mission designer want that to be possible. The cold border will normally be placed along the FLOT. Similar to what is currently in OPUF.
- All squadrons are represented in the .miz by a late activated aircraft that can be changed by the mission designer (loadout, type of aircraft, skin). Similar to what is currently in OPUF.
- Having an option to set a number of availeble aircraft in the script (to take into account shot down aircraft), and then having the readiness state adjust how many aircrafts that are availeble for tasking.

**Reference:**
Changing border during game:
https://www.youtube.com/watch?v=tfrdOMJSo6s&feature=youtu.be

OPUF AI A2A Dispacther reference:
https://github.com/132nd-vWing/OPUF/issues/14

**Comment by 132ndNeck** [comment]
@132nd-Entropy 
Me and Assaf have started working on this campaign now (and although the .miz is not availeble yet, since it will be based in the new Syrian map), I just want to see if you are able to start looking into this.

Also Skynet now have a Moose AI A2A dispatcher connecter. So if possible it would be great if you can look into this from your end.

**Comment by 132nd-Entropy** [comment]
WILCO!

**Comment by 132ndNeck** [comment]
> 
> 
> WILCO!

Excellent, thanks! Let me know if you need som clarification or explanation on how I envision this.

**Comment by 132ndNeck** [comment]
I see Moose have gotten some new functions / classes (?): Ops flightgroup, Ops auftrag, ops airwing.

It looks like some of these is something that can be used in stead if the AI A2A dispatcher if it is better?

**Comment by 132ndNeck** [comment]
With Syria map beeing soon released, we are stepping up effort for the campaign.
Details for the campaign is in these 2 briefs and contain information how airfields and squadrons will be setup.

What will be important is to tie the EWR coverage from the IADS (skynet) into the launching for Interceptor aircraft, or vectoring airborne CAPs.

[INTREP VIS OPAR-003 - Syrian Air Force - DRAFT 3.pdf](https://github.com/132nd-vWing/OPAR/files/5092783/INTREP.VIS.OPAR-003.-.Syrian.Air.Force.-.DRAFT.3.pdf)
[INTREP VIS OPAR-002 - Syrian IADS - DRAFT.pdf](https://github.com/132nd-vWing/OPAR/files/5092784/INTREP.VIS.OPAR-002.-.Syrian.IADS.-.DRAFT.pdf)

**Comment by 132nd-Entropy** [comment]
ok, I will definitely start looking into this finally

**Comment by 132ndNeck** [comment]
**Reworked request for the script**
After having worked on the .miz now for 2 events, and starting to get a good understanding of how this works, I will rework the request for the script functionality here in this post. What is written above can be used for reference and inspiration, but for the actual script in the OPAR .miz I request the following:

Baseline for the script will be similar to what is in the OPUF script (written by Pikes):
1. CAP
- A way to randomly select 1-2 of the airfields that will launch a CAP. Cap zone set in the .miz by a unit or triggerzone (similar to OPUF)
2. Cold border
- Similar to OPUF
3. QRA (GCI)
- A way to select 2-3 of the availeble airfields (not commented out) that will launch a QRA. (If possible, make customizable so mission designer can set fewer or more airfields)
- Time from detection until launch / airborne between 12-20 minutes, with the aim to be 15 minutes  (can also be made customizable in the scriptfile, so the mission designer can adjust the values)
- After launch of one QRA, if enemy are still detected within the cold border area, start QRA #2 from the same airfield. Launch 25-35 minutes after initial detection . If Blue forces are returning back outside the cold border, have the second QRA return to base and set a new 15 minute alert.
4. Tied to Skynet (as referenced above)
5. QRA and CAP is customizable in the .miz (selecting ordnance and skins) per airbase (similar to OPUF)


Airfields: (with option to comment out in the script file, similar to OPUF)
This is where QRA and CAP are based and launch from
- Jirah
- Tabqah
- Abu Ul Duhur
- Hama
- An Nasiryah
- Al Dumary
- Khalkalah
- Marj Ruhayl


**What I what to achieve is the following:**
- Enemy have 0-2 CAPs at any time in the airspace protecting Syria.
- On alert they have 2-3 QRA with a 15 minute ground alert. 
- If EWRs from skynet detect incoming fighters crossing the cold border, the CAP (if airborne) is launched to intercept. If there are more than 1 blue group crossing the border, QRA fighters are beeing scrambled
- Continious Blue prescence in  Syrian airspace (on Syrian side of the cold border) should increase pressure on blue flights, with more launches trying to get blue out of Syrian airspace

**Comment by 132nd-Entropy** [comment]
ok what I have so far

- one airfield from the above will have CAP
- there is a 50% chance a second Airfield will also have CAP
- CAP will launch when any blue planes are detected by Skynet AND if they are within the Cold Border (this is defined by an aircraft with the name cold border and needs to be adjusted

Each airfield above will need to have a zone, where the CAP will enter its racetrack when not fighting, all zones are in the top right corner of the map and should be moved, name must remain the same. 

so far, it will only spawn Mig29s, Im not getting different templates to work but I will ask in moose chat

**Comment by 132nd-Entropy** [comment]
ok, now each CAP-enabled airfield has a late-activated template group with the name Cap_xxxx
where xxx is the name of the airfield. The location of this template is irrelevant, the name needs to be kept, but the plane type and loadout can be easily changed in the ME.
