### ISSUE TITLE
Syrian Air Defence Forces order of battle (OOB)

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/OPAR#11]
This issue will be for agreeing on the structure of the Syrian Air Defence Forces (ADF)

I suggest to break the Syrian IADS into 3 seperate regions like this:
![bilde](https://user-images.githubusercontent.com/26002570/87552625-3aba7d00-c6b2-11ea-871c-11b2e8681e5f.png)

And then have each region with various SAMs to protect high value targets (such as airfields, command centres, bases, etc).
But that job is better on the .miz have dropped and we can place SAMs in the .miz and find good compromises.

Region South will be the most heavily defended of course, protecting Damascus, but all regions are connected by the commandcenter.

For targeting, taking out the power supply will take out the IADS and make the various SAMs go autonomous (and thus dumber). Same with the nodes, taking out a node will disconnect the region from the IADS and the SAMs in that region go autonomous (some will stay dark, some will go active)
Also, taking out the EWR sites prevents the IADS from getting data to turn on the SAMs, so that is also a viable tactic for pre-planned strikes.

**Comment by IAFAssafB** [comment]
Looks good.
Once the map is released I suggest that the borders between the areas covered by the nodes be adopted to geographic terrain. It can provide a nice challenge for VIS/ planning of how to spot the dead zones and plan ingress for deep strikes based on that analysis.
Also suggest that the nodes/power-sources would be built as hardened facilities (Command bunkers with perhaps some fuel tanks outside etc).

**Comment by 132ndNeck** [comment]
> 
> 
> Also suggest that the nodes/power-sources would be built as hardened facilities (Command bunkers with perhaps some fuel tanks outside etc).

Yes, Nodes will be typical commstowers or command bunkers, The command center will be the commandbunkers (or several of them together). And the powersource will normally be a powerplant.
Will also, do some testing and experimenting with skynet to see if several powersources can be connected, so all need to be destroyed (so primary the powerplant, and the a secondary option with some generators for example).

Will provide plenty of good/challenging targets

**Comment by IAFAssafB** [comment]
Regarding the powerplants- I've found this (generator of an old UK command bunker). I think having square,simple-looking buildings near the actual command bunkers could be more realistic as those simple structures are less distinct than the DCS powerplants (I think one of the "bunker" structure types in DCS can be used for that).
As for redundancies and interconnecting of powerplants and command nodes - sounds awesome and will definitely improve the challenge and the thinking required about attacking those.
![image](https://user-images.githubusercontent.com/42184209/87656762-96444380-c762-11ea-8ef4-f68d8c2e0511.png)

**Comment by 132ndNeck** [comment]
> 
> 
> Regarding the powerplants- I've found this (generator of an old UK command bunker). I think having square,simple-looking buildings near the actual command bunkers could be more realistic as those simple structures are less distinct than the DCS powerplants (I think one of the "bunker" structure types in DCS can be used for that).
> As for redundancies and interconnecting of powerplants and command nodes - sounds awesome and will definitely improve the challenge and the thinking required about attacking those.
> 

Great, if able, are you able to provide me of a screenshot of the type of house from DCS? That way I can include it in the IADS intelligence briefing I am producing.
No rush, and I can fix it later this week when I am back home in front of my DCS computer
