### ISSUE TITLE
RL background : Israel/Syria/Iran/Lebanon 

### ISSUE THREAD

**Issue by IAFAssafB** [132nd-vWing/OPAR#12]
I wonder if it would add something to immersion of other participants if I prepare/conduct a short TS review of the recent conflicts involving Israel/Iran/Syria/Lebanon and how they affect/interact with each other.
Obviously steer away of politics but I think a description of how previous conflict looked like could underline importance of certain sites/geographic features  , the courses of actions by all parties etc.

**Comment by 132ndNeck** [comment]
I think that would be interesting and good for everyone to listen to, and I would very much be interested in your perspectives on this matter.
However, I am sceptical to include that as part of the campaign. I want to have a very clear seperation between the real world and this campaign. And this campaign is inspired by real events, but is not replicating it, as we then is locking ourself in more than we need to.

I think such a brief would be very relevant for all operations on the new Syrian map, so I suggest you move forward with it, but not connected to the campaign. 

But a good idea, which we have not done before, is to have a introductionary brief to the campaign. Giving the situation, some basic intel, and admin information. Could be conducted multiple times the week leading up to the campaign.

**Comment by IAFAssafB** [comment]
Thanks,
This makes perfect sense. I'm totally happy to prepare and deliver this once the map is released and I can actually share a desktop and show how it looks like on the DCS world map and terrain.
I can include a general overview of all forces involved and how previous RL conflicts looked like. By giving it before we start the campaign this might - or might not- hint as to how a some events in the campaign _might_ look like. It would probably give the VIS/CJTF HQ more things to consider and have in mind (and worry about :-P ) when planning/ anticipating enemy moves. 

Some examples:
1) What is Hezbollah, where it sits , what it does.
2) What are proxy organizations and how Iran is using them.
3) Strategic importance of the Golan Heights, Mt Hermon and the volcanic hills-lines.

Past conflicts and operations:
2) The Syrian use of commando raids in the 1973 war (Mt. Hermon, the Jordan-river bridges, key junctions)
3) Hezbollah's tactics (artillery, small scale raids, underground tunnels)

**Comment by 132ndNeck** [comment]
That sounds really good! I look forward to it already!
