### ISSUE TITLE
Create background/scenario/situation

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/OPAR#3]
Campaign need a background to give the context for immersion, and to provide inputs for the intelligence section.

**Blue coalition**
- Israel
- Turkey
- Jordan (consider if it should be on red or blue)

Main coalition airbases:
Incerlik (Turkey)
Ramat David (Israel)
+ Carrier Strike Group

**Red coalition**
- Syria  
- Russia
- Syria
- China

**Neutral coalition:** 
- Libanon

**Scenario need to facilitate for:**
- Ground combat (high intensity) in several areas (for example north to the border of Turkey + On border to Israel/Jordan)
- Ground combat (low intensity - Counter insurgency operations)
- Deep strikes / A-A / non-permissive (entire Syria territory)

**Ideas:**
- Route from Raqqa to Homs and then further to Lebanon can be a route used for smuggling and logistics for Iranian proxies in Lebanon.  Several mission types can then be conducted toward this based on intel or other triggers.

**Comment by 132ndNeck** [comment]
From @IAFAssafB 
![bilde](https://user-images.githubusercontent.com/26002570/87295433-75cb7d80-c505-11ea-88aa-c32dd93d64ac.png)

**Comment by 132ndNeck** [comment]
Suggest the following Syrian order of battle (OOB)

# Syrian Army

**1st Corps  (Task to seize Iskenderun)**
- 10th Armored Division (T-72)
- 11th Mechanized Division (BMP-2)
- 12th Motorized Division (BTR-80)
- 13th Air Defense Division
- 14th Rocket artillery regiment
- 15th Reconnaissance Regiment
- 16th Helicopter Regiment
- 17th Logistics Regiment



**2nd Corps (task to seize and secure oilfields and eletric generating dam)**
- 21th Mechanized Division (BMP-1)
- 22nd Motorized Division (BTR-80)
- 27th Logistics Regiment
- 25th Reconnaissance Regiment
- 26th Helicopter Regiment


**3rd Corps (task to attack and seize the Golan heights)**
- 30th Armored Division (T-72)
- 31th Mechanized Division (BMP-2)
- 32nd Motorized Division (BTR-80)
- 33rd Air Defense Division
- 34th Rocket artillery regiment
- 35th Reconnaissance Regiment
- 36th Helicopter Regiment
- 37th Logistics Regiment

**4th Corps  (Protection of Damascus, and reinforcements)**
- 41st Mechanized Division (BMP-1)
- 42nd Mechanized Division (BMP-3)
- 43rd Motorized Division (BTR-80)



## INDEPENDENT UNITS
- Republican Guard Armored Division (Strategic reserve), Damascus?  (T-80)
- Surface-to-Surface Missile Regiment, SCUDs (High Value Targets, unlocated)
- Surface-to-Surface Missile Regiment, SCUDs  (High Value Targets, unlocated)
- Special Forces Brigade

**Comment by 132ndNeck** [comment]
# 1st Corps (Task to seize Iskenderun)

## 10th Armored Division (T-72)
**101th Armor Brigade**
- 1011 Armor BN
- 1012 Armor BN
- 1013 Armor BN
- 1014 Artillery BN
- 1061st Air Defence BN  (from 106th Air Defence Regiment)

**102nd Armor Brigade**
- 1021 Armor BN
- 1022 Armor BN
- 1023 Armor BN
- 1024 Artillery BN
- 1062nd Air Defence BN  (from 106th Air Defence Regiment)

**103rd Armor Brigade**
- 1031 Armor BN
- 1032 Armor BN
- 1033 Armor BN
- 1034 Artillery BN
- 1063rd Air Defence BN  (from 106th Air Defence Regiment)

**104th Logistics battalion**

**105th Rocket Artillery Battalion**

**151st Recon BN (From 15th Recon Regiment)**

**106th Air Defence Regiment**
_- 1061st Air Defence BN  (attached to 101st Armored Brigade)_
_- 1062nd Air Defence BN (attached to 102nd Armored Brigade)_
_- 1063rd Air Defence BN (attached to 103rd Armored Brigade)_
- 1064th SA-8 BN
- 1065th SA-15 BN




## 11th Mechanized Division (BMP-2)
**111th Mechanized Brigade**
- 1111th Mechanized BN
- 1112th Mechanized BN
- 1113th Mechanized BN
- 1114th Artillery BN
- 1161st Air Defence BN  (from 116th Air Defence Regiment)

**112th Mechanized Brigade**
- 1121st Mechanized BN
- 1122nd Mechanized BN
- 1123rd Mechanized BN
- 1124th Artillery BN
- 1162nd Air Defence BN  (from 116th Air Defence Regiment)

**113th Mechanized Brigade**
- 1131st Mechanized BN
- 1132nd Mechanized BN
- 1133rd Mechanized BN
- 1134th Artillery BN
- 1163nd Air Defence BN  (from 116th Air Defence Regiment)

**114th Logistics battalion**

**115th Rocket Artillery Battalion**

- 152nd Recon BN (attached to 11th Mechanized Division)

**116th Air Defence Regiment**
_- 1161st Air Defence BN  (attached to 111st Mechanized Brigade)_
_- 1162nd Air Defence BN  (attached to 112th Mechanized Brigade)_
_- 1163rd Air Defence BN  (attached to 113th Mechanized Brigade)_
- 1164th SA-8 BN
- 1165th SA-15 BN




## 12th Motorized Division (BTR-80)
**121st Motorized Brigade**
- 1211th Mechanized BN
- 1212th Mechanized BN
- 1213th Mechanized BN
- 1214th Artillery BN
- 1261st Air Defence BN  (from 126th Air Defence Regiment)

**122nd Motorized Brigade**
- 1221st Mechanized BN
- 1222nd Mechanized BN
- 1223rd Mechanized BN
- 1224th Artillery BN
- 1262st Air Defence BN  (from 126th Air Defence Regiment)

**123nd Motorized Brigade**
- 1231st Mechanized BN
- 1232nd Mechanized BN
- 1233rd Mechanized BN
- 1234th Artillery BN
- 1263st Air Defence BN  (from 126th Air Defence Regiment)

**124th Logistics battalion**

**125th Rocket Artillery Battalion**

- 153rd Recon BN (attached to 12th Motorized Division)

**126th Air Defence Regiment**
_- 1261st Air Defence BN  (attached to 121st Motorized Brigade)_
_- 1262nd Air Defence BN  (attached to 122th Motorized Brigade)_
_- 1263rd Air Defence BN  (attached to 123rd Motorized Brigade)_
- 1164th SA-8 BN
- 1165th SA-15 BN




## 13th Air Defense Division
- 106th Air Defence Regiment (Attached to 10th Armored Division)
_-  XXX Air Defence Regiment (Attached to 11th Mechanized Division)_
_-  XXX Air Defence Regiment (Attached to 12th Motorized Division)_
- 131st SA-6 BN
- 132nd SA-11 BN
- 133rd HQ BN




## 14th Rocket artillery regiment
- 141st Heavy Rocket Artillery BN
- 142nd Heavy Rocket Artillery BN




## 15th Reconnaissance Regiment
_- 151st Recon BN (attached to 10th Armored Division)_
_- 152nd Recon BN (attached to 11th Mechanized Division)_
_- 153rd Recon BN (attached to 12th Motorized Division)_
- 154th Long Range Recon BN
- 156th Special Recon BN




## 16th Helicopter Regiment
- 161st AHS (Attack Helicopter Squadron)
- 162nd THS (Transport Helicopter Squadron
- 163rd THS 




## 17th Logistics Regiment
-171st FARP BN
-172nd Medical BN
-173rd Logistics BN
- 174th Logistics BN
- 175th Logistics BN

**Comment by IAFAssafB** [comment]
@132ndNeck referencing your Discord comments for the background story:
1) Ref' timing for involvement of Russia an Iran: 
 I suggest having something that resembles current RL state (i.e minor presence of Russian airforce and air-defense advisors. Russian advisors situated mostly in one of the airbases (where we can have Russian-unique equipment - aircraft and air defenses like SA15 and alike). Iranian involvement is primarily to the SOUTH, sort of trying to establish a corridor between Iran and Israel borders (some logistical camps and perhaps minor presence of long-range artillery but nothing too overt).

2) I like the idea of having first mission as a joint training with Israeli/Turkish forces and then shortly afterwards things begin to go sour with more skirmishes occurring along borders and increased activity by Hizballah and Iranian proxies.
Then, Russian declares cutting diplomatic ties, commences hostilities against US satellites above the middle-east (jamming?) and at the same time mobilizing much more airforce , air defense units into Syria while Iran dispatches its supporting corps in anticipation for a full scale war. Those foreign "extra" forces can be committed into battle on 3rd or 4th campaign mission (takes time for buildup of forces while at the same time Syrian forces starting to engage in battle in one of the fronts.

Let me know what you think. If it makes sense then I shall re-write the draft with more details/ timeline.

**Comment by 132ndNeck** [comment]
> 
>     1. Ref' timing for involvement of Russia and Iran:
>        I suggest having something that resembles current RL state (i.e minor presence of Russian airforce and air-defense advisors. Russian advisors situated mostly in one of the airbases (where we can have Russian-unique equipment - aircraft and air defenses like SA15 and alike). Iranian involvement is primarily to the SOUTH, sort of trying to establish a corridor between Iran and Israel borders (some logistical camps and perhaps minor presence of long-range artillery but nothing too overt).
> 


I suggest to make sure in the order of battle to specify what kind of equipment that belong to Syria. Also, I suggest to make simplified version/adjusting from the real world to simplify both for us as the mission designers, but also all the pilots.
So, I suggest to follow the generic order of battle as much as possible. So our case, the air defence regiment have SA-15s. 

The biggest thing to seperate russian participation will be T-90s, Airborne units and various air assets/sea assets.

I suggest Russia to have a base at Tartus (naval base) and Bassel Al-Assad Airport (Close to Latakia). Where they have a small detachement of advisors and few units to support the Syrian regime. As the conflict increases , later in the campaign, then reinforcements can come either from the EAST into new bases or the WEST into these bases from the sea

**Comment by 132ndNeck** [comment]
> 
>     2. I like the idea of having first mission as a joint training with Israeli/Turkish forces and then shortly afterwards things begin to go sour with more skirmishes occurring along borders and increased activity by Hizballah and Iranian proxies.
>        Then, Russian declares cutting diplomatic ties, commences hostilities against US satellites above the middle-east (jamming?) and at the same time mobilizing much more airforce , air defense units into Syria while Iran dispatches its supporting corps in anticipation for a full scale war. Those foreign "extra" forces can be committed into battle on 3rd or 4th campaign mission (takes time for buildup of forces while at the same time Syrian forces starting to engage in battle in one of the fronts.
> 
> 

I suggest that we dont plan yet on when to bring in the reinforcements. Currently the Syrian Corps in place should provide enough targets for several missions. Also, with the added CAS missions in Lebanon against insurgent groups, it should be a lot of stuff to do, and then we can slowly start dropping indicators as the campaign progress.

So immediatly after mission 1, the war breaks out, and Syria starts the invasion. Iran and Russia provides diplomatic and political support, but we dont see any military activity besides what is already there.

I want this campaign to go on for a long time, so dont want us to rush into something forcing us to quit it early.

This will give us options where you host a mission focused around Israel/Lebanon/Syria, while I focus missions focused on the northern part of the map.  And we can take turns, and of course also add taskings in all areas as we see fit on all missions. (I just want to make it flexible to make it easier to keep it going and work for the both of us.)

So I suggest we will seperate the map in 2, and have me responsible in the north (turkey), and you in the south (israel). Does that make sense and is a smart approach?

**Comment by IAFAssafB** [comment]
> > ```
> > 2. I like the idea of having first mission as a joint training with Israeli/Turkish forces and then shortly afterwards things begin to go sour with more skirmishes occurring along borders and increased activity by Hizballah and Iranian proxies.
> >    Then, Russian declares cutting diplomatic ties, commences hostilities against US satellites above the middle-east (jamming?) and at the same time mobilizing much more airforce , air defense units into Syria while Iran dispatches its supporting corps in anticipation for a full scale war. Those foreign "extra" forces can be committed into battle on 3rd or 4th campaign mission (takes time for buildup of forces while at the same time Syrian forces starting to engage in battle in one of the fronts.
> > ```
> 
> I suggest that we dont plan yet on when to bring in the reinforcements. Currently the Syrian Corps in place should provide enough targets for several missions. Also, with the added CAS missions in Lebanon against insurgent groups, it should be a lot of stuff to do, and then we can slowly start dropping indicators as the campaign progress.
> 
> So immediatly after mission 1, the war breaks out, and Syria starts the invasion. Iran and Russia provides diplomatic and political support, but we dont see any military activity besides what is already there.
> 
> I want this campaign to go on for a long time, so dont want us to rush into something forcing us to quit it early.
> 
> This will give us options where you host a mission focused around Israel/Lebanon/Syria, while I focus missions focused on the northern part of the map. And we can take turns, and of course also add taskings in all areas as we see fit on all missions. (I just want to make it flexible to make it easier to keep it going and work for the both of us.)
> 
> So I suggest we will seperate the map in 2, and have me responsible in the north (turkey), and you in the south (israel). Does that make sense and is a smart approach?

Makes perfect sense to me. Having Iran and Russia joining the party later on provides much more flexibility, as the movement of such large forces takes a long time (Weeks probably) so it gives a long time for us to "tip" the intl officer with hints for this movement and for whoever decides on the mission objectives to target and harass those movements (strike airbases, bridges, roads, logistics etc etc).

**Comment by IAFAssafB** [comment]
For our use I think it's good to outline what we expect to happen on the enemy side during the campaign.
Proposed format shown here. Needless to say we're not bound by the timeline and can nudge events further down or up a little (I.e from D+5 to D+6 or 7) - depending on how the wing performs and what operations we get to actually execute. The idea is for us to have a general scope of the events.
The intent is to include just high-level/bullets in each box so that in the days prior to a specific events we can look at it, generate INTL reports which reflect what's on that table and deliver them to the VIS office.
If it makes sense then I'll start filling it up. 
![image](https://user-images.githubusercontent.com/42184209/87726635-105ae380-c7c8-11ea-9572-cf208048f66f.png)

**Comment by 132ndNeck** [comment]
> 
> 
> For our use I think it's good to outline what we expect to happen on the enemy side during the campaign.
> Proposed format shown here. Needless to say we're not bound by the timeline and can nudge events further down or up a little (I.e from D+5 to D+6 or 7) - depending on how the wing performs and what operations we get to actually execute. The idea is for us to have a general scope of the events.
> The intent is to include just high-level/bullets in each box so that in the days prior to a specific events we can look at it, generate INTL reports which reflect what's on that table and deliver them to the VIS office.
> If it makes sense then I'll start filling it up.

Great idea! 
I suggest we have this as a mission designer file only. So I can create a google doc and give you access. That way no one can unintentionally see what is planned :)

**Comment by 132ndNeck** [comment]
I was thinking a little. Maybe it will be easier to start the campaign after an initial Syrian assault toward the Goland heights. And CJTF-82 is deployed to deter further action (similar to Desert Shield), while CJTF builds up combat forces to conduct a counteroffensive, and then during mission 2, the Syrians starts the offiensive also in the North?
