### ISSUE TITLE
Syrian ground order of battle (OOB)

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/OPAR#5]
This post contain the big picture Syrian ground forces.
See additional posts below for additional details and breakout of the various Corps and divisions. All is based on the generic enemy ground force document:
- https://github.com/132nd-vWing/VIS/blob/master/BASIC/PUBLISHED/INTREP%20VIS%20B-001%20Generic%20Ground%20Force%20Structure%20v1.0.pdf 

<br>

- The additonal posts breaks the Syrian units down to battalion level, so all battalions for a Corps is listed in the specific post for that Corps.
- For some of the Corps there are some deviations (do not have the full Corps structure as given in the generic ground force document. But the specific post shows the breakdown of the Corps and what it contains.

# Syrian Army

**1st Corps  (Task to seize Iskenderun)**
- 10th Armored Division (T-72)
- 11th Mechanized Division (BMP-2)
- 12th Motorized Division (BTR-80)
- 13th Air Defense Division
- 14th Rocket artillery regiment
- 15th Reconnaissance Regiment
- 16th Helicopter Regiment
- 17th Logistics Regiment

**2nd Corps (task to seize and secure oilfields and eletric generating dam)**
- 21th Mechanized Division (BMP-1)
- 22nd Motorized Division (BTR-80)
- 27th Logistics Regiment
- 25th Reconnaissance Regiment
- 26th Helicopter Regiment

**3rd Corps (task to attack and seize the Golan heights)**
- 30th Armored Division (T-72)
- 31st Mechanized Division (BMP-2)
- 32nd Motorized Division (BTR-80)
- 33rd Air Defense Division
- 34th Rocket artillery regiment
- 35th Reconnaissance Regiment
- 36th Helicopter Regiment
- 37th Logistics Regiment

**4th Corps  (Protection of Damascus, and reinforcements)**
- 41st Mechanized Division (BMP-1)
- 42nd Mechanized Division (BMP-3)
- 43rd Motorized Division (BTR-80)

**5th Corps  (Republican Guard) - Based Palmyra. Strategic Reserve)**
- 50th Armored Division (T-72)
- 51st Armored Division (T-72)
- 52th Mecahnized Division (BMP-2)
- 53rd Air Defense Division
- 54th Rocket artillery regiment
- 55th Reconnaissance Regiment
- 56th Helicopter Regiment
- 57th Logistics Regiment

## INDEPENDENT UNITS
- 91st Republican Guard Armored Division (Strategic reserve), Damascus?  (T-80)
- 922nd Surface-to-Surface Missile Regiment, SCUDs (High Value Targets, unlocated)
- 923rd Surface-to-Surface Missile Regiment, SCUDs  (High Value Targets, unlocated)
- 924th Surface-to-Surface Missile Regiment, SCUDs  (High Value Targets, unlocated)
- 931th Special Forces Brigade

**Comment by 132ndNeck** [comment]
# 1st Corps (Task to seize Iskenderun)

## 10th Armored Division (T-72)
**101st Armor Brigade**
- 1011 Armor BN
- 1012 Armor BN
- 1013 Armor BN
- 1014 Artillery BN
- 1061st Air Defence BN  (from 106th Air Defence Regiment)

**102nd Armor Brigade**
- 1021 Armor BN
- 1022 Armor BN
- 1023 Armor BN
- 1024 Artillery BN
- 1062nd Air Defence BN  (from 106th Air Defence Regiment)

**103rd Armor Brigade**
- 1031 Armor BN
- 1032 Armor BN
- 1033 Armor BN
- 1034 Artillery BN
- 1063rd Air Defence BN  (from 106th Air Defence Regiment)

**104th Logistics battalion**

**105th Rocket Artillery Battalion**

**151st Recon BN (From 15th Recon Regiment)**

**106th Air Defence Regiment**
-  _1061st Air Defence BN  (**attached** to 101st Armored Brigade)_
- _1062nd Air Defence BN (**attached** to 102nd Armored Brigade)_
- _1063rd Air Defence BN (**attached** to 103rd Armored Brigade)_
- 1064th SA-8 BN
- 1065th SA-15 BN




## 11th Mechanized Division (BMP-2)
**111th Mechanized Brigade**
- 1111th Mechanized BN
- 1112th Mechanized BN
- 1113th Mechanized BN
- 1114th Artillery BN
- 1161st Air Defence BN  (from 116th Air Defence Regiment)

**112th Mechanized Brigade**
- 1121st Mechanized BN
- 1122nd Mechanized BN
- 1123rd Mechanized BN
- 1124th Artillery BN
- 1162nd Air Defence BN  (from 116th Air Defence Regiment)

**113th Mechanized Brigade**
- 1131st Mechanized BN
- 1132nd Mechanized BN
- 1133rd Mechanized BN
- 1134th Artillery BN
- 1163nd Air Defence BN  (from 116th Air Defence Regiment)

**114th Logistics battalion**

**115th Rocket Artillery Battalion**

- 152nd Recon BN (attached to 11th Mechanized Division)

**116th Air Defence Regiment**
-  _1161st Air Defence BN  (**attached** to 111st Mechanized Brigade)_
-  _1162nd Air Defence BN  (**attached** to 112th Mechanized Brigade)_
-  _1163rd Air Defence BN  (**attached** to 113th Mechanized Brigade)_
- 1164th SA-8 BN
- 1165th SA-15 BN




## 12th Motorized Division (BTR-80)
**121st Motorized Brigade**
- 1211th Motorized BN
- 1212th Motorized BN
- 1213th Motorized BN
- 1214th Artillery BN
- 1261st Air Defence BN  (from 126th Air Defence Regiment)

**122nd Motorized Brigade**
- 1221st Motorized BN
- 1222nd Motorized BN
- 1223rd Motorized BN
- 1224th Artillery BN
- 1262st Air Defence BN  (from 126th Air Defence Regiment)

**123nd Motorized Brigade**
- 1231st Motorized BN
- 1232nd Motorized BN
- 1233rd Motorized BN
- 1234th Artillery BN
- 1263st Air Defence BN  (from 126th Air Defence Regiment)

**124th Logistics battalion**

**125th Rocket Artillery Battalion**

- 153rd Recon BN (attached to 12th Motorized Division)

**126th Air Defence Regiment**
- _1261st Air Defence BN  (**attached** to 121st Motorized Brigade)_
- _1262nd Air Defence BN  (**attached** to 122th Motorized Brigade)_
- _1263rd Air Defence BN  (**attached** to 123rd Motorized Brigade)_
- 1264th SA-8 BN
- 1265th SA-15 BN




## 13th Air Defense Division
- _106th Air Defence Regiment (**Attached** to 10th Armored Division)_
-  _116th Air Defence Regiment (**Attached** to 11th Mechanized Division)_
-  _126th Air Defence Regiment (**Attached** to 12th Motorized Division)_
- 131st SA-6 BN
- 132nd SA-11 BN
- 133rd HQ BN




## 14th Rocket artillery regiment
- 141st Heavy Rocket Artillery BN
- 142nd Heavy Rocket Artillery BN




## 15th Reconnaissance Regiment
- _151st Recon BN (**attached** to 10th Armored Division)_
- _152nd Recon BN (**attached** to 11th Mechanized Division)_
- _153rd Recon BN (**attached** to 12th Motorized Division)_
- 154th Long Range Recon BN
- 156th Special Recon BN




## 16th Helicopter Regiment
- 161st AHS (Attack Helicopter Squadron) - MI-24
- 162nd THS (Transport Helicopter Squadron - MI-26
- 163rd THS - MI-26




## 17th Logistics Regiment
- 171st FARP BN
- 172nd Medical BN
- 173rd Logistics BN
- 174th Logistics BN
- 175th Logistics BN

**Comment by 132ndNeck** [comment]
# 2nd Corps (task to seize and secure oilfields and eletric generating dam)
<br>

## 21st Mechanized Division (BMP-1)
**211th Mechanized Brigade**
- 2111st Mechanized BN
- 2112nd Mechanized BN
- 2113rd Mechanized BN
- 2114th Artillery BN
- 2161st Air Defence BN (from 216th Air Defence Regiment) 

**212th Mechanized Brigade**
- 2121 Mechanized BN
- 2122 Mechanized BN
- 2123 Mechanized BN
- 2124 Mechanized BN
- 2162nd Air Defence BN  (from 216th Air Defence Regiment)

**213th Mechanized Brigade**
- 2131 Mechanized BN
- 2132 Mechanized BN
- 2133 Mechanized BN
- 2134 Artillery BN
- 2163rd Air Defence BN  (from 216th Air Defence Regiment)

**214th Logistics battalion**

**215th Rocket Artillery Battalion**

**251st Recon BN (From 25th Recon Regiment)**

**216th Air Defence Regiment**
-  _2161st Air Defence BN  (**attached** to 211st Mechanized Brigade)_
- _2162nd Air Defence BN (**attached** to 212nd Mechanized Brigade)_
- _2163rd Air Defence BN (**attached** to 213rd Mechanized Brigade)_
- 2164th SA-8 BN
- 2165th SA-15 BN


<br>
<br>
<br>


## 22nd Motorized Division (BTR-80)
**221st Motorized  Brigade**
- 2211th Motorized  BN
- 2212th Motorized  BN
- 2213th Motorized  BN
- 2214th Artillery BN
- 2261st Air Defence BN  (from 226th Air Defence Regiment)

**222nd Motorized  Brigade**
- 2221st Motorized  BN
- 2222nd Motorized  BN
- 2223rd Motorized  BN
- 2224th Artillery BN
- 2262nd Air Defence BN  (from 226th Air Defence Regiment)

**223rdMotorized  Brigade**
- 2231st Motorized  BN
- 2232nd Motorized  BN
- 2233rd Motorized  BN
- 2234th Artillery BN
- 2263nd Air Defence BN  (from 226th Air Defence Regiment)

**224th Logistics battalion**

**225th Rocket Artillery Battalion**

**252st Recon BN (From 25th Recon Regiment)**

**226th Air Defence Regiment**
-  _2261st Air Defence BN  (**attached** to 221st Mechanized Brigade)_
-  _2262nd Air Defence BN  (**attached** to 222th Mechanized Brigade)_
-  _2263rd Air Defence BN  (**attached** to 223th Mechanized Brigade)_
- 2264th SA-8 BN
- 2265th SA-15 BN



<br>
<br>
<br>


## 25th Reconnaissance Regiment
- _251st Recon BN (**attached** to 21th Mechanized Division)_
- _252nd Recon BN (**attached** to 22nd Motorized Division)_
- 254th Long Range Recon BN
- 256th Special Recon BN

<br>
<br>



## 26th Helicopter Regiment
- 261st AHS (Attack Helicopter Squadron) - MI-24
- 262nd THS (Transport Helicopter Squadron - MI-26
- 263rd THS - MI-26

<br>
<br>



## 27th Logistics Regiment
- 271st FARP BN
- 272nd Medical BN
- 273rd Logistics BN
- 274th Logistics BN
- 275th Logistics BN

**Comment by 132ndNeck** [comment]
# 3rd Corps (task to attack and seize the Golan heights)

## 30th Armored Division (T-72)
**301st Armor Brigade**
- 3011th Armor BN
- 3012th Armor BN
- 3013th Armor BN
- 3014th Artillery BN
- 3061st Air Defence BN  (from 306th Air Defence Regiment)

**302nd Armor Brigade**
- 3021st Armor BN
- 3022nd Armor BN
- 3023rd Armor BN
- 3024th Artillery BN
- 3062nd Air Defence BN  (from 306th Air Defence Regiment)

**303rd Armor Brigade**
- 3031st Armor BN
- 3032nd Armor BN
- 3033rd Armor BN
- 3034th Artillery BN
- 3063rd Air Defence BN  (from 306th Air Defence Regiment)

**304th Logistics battalion**

**305th Rocket Artillery Battalion**

**351st Recon BN (From 35th Recon Regiment)**

**306th Air Defence Regiment**
-  _3061st Air Defence BN  (**attached** to 301st Armored Brigade)_
- _3062nd Air Defence BN (**attached** to 302nd Armored Brigade)_
- _3063rd Air Defence BN (**attached** to 303rd Armored Brigade)_
- 3064th SA-8 BN
- 3065th SA-15 BN




## 31th Mechanized Division (BMP-2)
**311th Mechanized Brigade**
- 3111th Mechanized BN
- 3112th Mechanized BN
- 3113th Mechanized BN
- 3114th Artillery BN
- 3161st Air Defence BN  (from 316th Air Defence Regiment)

**312th Mechanized Brigade**
- 3121st Mechanized BN
- 3122nd Mechanized BN
- 3123rd Mechanized BN
- 3124th Artillery BN
- 3162nd Air Defence BN  (from 316th Air Defence Regiment)

**313th Mechanized Brigade**
- 3131st Mechanized BN
- 3132nd Mechanized BN
- 3133rd Mechanized BN
- 3134th Artillery BN
- 3163nd Air Defence BN  (from 316th Air Defence Regiment)

**314th Logistics battalion**

**315th Rocket Artillery Battalion**

**352nd Recon BN (from 35th Reconnaissance Regiment)**

**316th Air Defence Regiment**
-  _3161st Air Defence BN  (**attached** to 311st Mechanized Brigade)_
-  _3162nd Air Defence BN  (**attached** to 312th Mechanized Brigade)_
-  _3163rd Air Defence BN  (**attached** to 313th Mechanized Brigade)_
- 3164th SA-8 BN
- 3165th SA-15 BN




## 32nd Motorized Division (BTR-80)
**321st Motorized Brigade**
- 3211th Mechanized BN
- 3212th Mechanized BN
- 3213th Mechanized BN
- 3214th Artillery BN
- 3261st Air Defence BN  (from 326th Air Defence Regiment)

**322nd Motorized Brigade**
- 3221st Mechanized BN
- 3222nd Mechanized BN
- 3223rd Mechanized BN
- 3224th Artillery BN
- 3262st Air Defence BN  (from 326th Air Defence Regiment)

**323nd Motorized Brigade**
- 3231st Mechanized BN
- 3232nd Mechanized BN
- 3233rd Mechanized BN
- 3234th Artillery BN
- 3263st Air Defence BN  (from 326th Air Defence Regiment)

**324th Logistics battalion**

**325th Rocket Artillery Battalion**

**353rd Recon BN (from 35th Reconnaissance Regiment)**

**326th Air Defence Regiment**
- _3261st Air Defence BN  (**attached** to 321st Motorized Brigade)_
- _3262nd Air Defence BN  (**attached** to 322th Motorized Brigade)_
- _3263rd Air Defence BN  (**attached** to 323rd Motorized Brigade)_
- 3264th SA-8 BN
- 3265th SA-15 BN




## 33rd Air Defense Division
- _306th Air Defence Regiment (**Attached** to 30th Armored Division)_
-  _316th Air Defence Regiment (**Attached** to 31st Mechanized Division)_
-  _326th Air Defence Regiment (**Attached** to 32nd Motorized Division)_
- 331st SA-6 BN
- 332nd SA-11 BN
- 333rd HQ BN




## 34th Rocket artillery regiment
- 341st Heavy Rocket Artillery BN
- 342nd Heavy Rocket Artillery BN




## 35th Reconnaissance Regiment
- _351st Recon BN (**attached** to 30th Armored Division)_
- _352nd Recon BN (**attached** to 31st Mechanized Division)_
- _353rd Recon BN (**attached** to 32nd Motorized Division)_
- 354th Long Range Recon BN
- 356th Special Recon BN




## 36th Helicopter Regiment
- 361st AHS (Attack Helicopter Squadron) - MI-24
- 362nd THS (Transport Helicopter Squadron - MI-26
- 363rd THS - MI-26




## 37th Logistics Regiment
- 371st FARP BN
- 372nd Medical BN
- 373rd Logistics BN
- 374th Logistics BN
- 375th Logistics BN

**Comment by 132ndNeck** [comment]
# 4th Corps (Protection of Damascus, and reinforcements)

<br>
<br>

## 41th Mechanized Division (BMP-1)
**411th Mechanized Brigade**
- 4111th Mechanized BN
- 4112th Mechanized BN
- 4113th Mechanized BN
- 4114th Artillery BN
- 4161st Air Defence BN  (from 416th Air Defence Regiment)

**412th Mechanized Brigade**
- 4121st Mechanized BN
- 4122nd Mechanized BN
- 4123rd Mechanized BN
- 4124th Artillery BN
- 4162nd Air Defence BN  (from 416th Air Defence Regiment)

**413th Mechanized Brigade**
- 4131st Mechanized BN
- 4132nd Mechanized BN
- 4133rd Mechanized BN
- 4134th Artillery BN
- 4163nd Air Defence BN  (from 416th Air Defence Regiment)

**414th Logistics battalion**

**415th Rocket Artillery Battalion**


**416th Air Defence Regiment**
-  _4161st Air Defence BN  (**attached** to 411st Mechanized Brigade)_
-  _4162nd Air Defence BN  (**attached** to 412th Mechanized Brigade)_
-  _4163rd Air Defence BN  (**attached** to 413th Mechanized Brigade)_
- 4164th SA-8 BN
- 4165th SA-15 BN

<br>
<br>
<br>

## 42nd Mechanized Division (BMP-3)
**421th Mechanized Brigade**
- 4211th Mechanized BN
- 4212th Mechanized BN
- 4213th Mechanized BN
- 4214th Artillery BN
- 4261st Air Defence BN  (from 426th Air Defence Regiment)

**422th Mechanized Brigade**
- 4221st Mechanized BN
- 4222nd Mechanized BN
- 4223rd Mechanized BN
- 4224th Artillery BN
- 4262nd Air Defence BN  (from 426th Air Defence Regiment)

**423th Mechanized Brigade**
- 4231st Mechanized BN
- 4232nd Mechanized BN
- 4233rd Mechanized BN
- 4234th Artillery BN
- 4263nd Air Defence BN  (from 426th Air Defence Regiment)

**424th Logistics battalion**

**425th Rocket Artillery Battalion**

**426th Air Defence Regiment**
-  _4261st Air Defence BN  (**attached** to 421st Mechanized Brigade)_
-  _4262nd Air Defence BN  (**attached** to 422th Mechanized Brigade)_
-  _4263rd Air Defence BN  (**attached** to 423th Mechanized Brigade)_
- 4264th SA-8 BN
- 4265th SA-15 BN


<br>
<br>
<br>

## 43rd Motorized Division (BTR-80)
**431th Motorized Brigade**
- 4311th Motorized BN
- 4312th Motorized BN
- 4313th Motorized BN
- 4314th Artillery BN
- 4361st Air Defence BN  (from 436th Air Defence Regiment)

**432nd Motorized Brigade**
- 4321st Motorized BN
- 4322nd Motorized BN
- 4323rd Motorized BN
- 4324th Artillery BN
- 4362nd Air Defence BN  (from 436th Air Defence Regiment)

**433th Motorized Brigade**
- 4331st Motorized BN
- 4332nd Motorized BN
- 4333rd Motorized BN
- 4334th Artillery BN
- 4363nd Air Defence BN  (from 436th Air Defence Regiment)

**434th Logistics battalion**

**435th Rocket Artillery Battalion**

**436th Air Defence Regiment**
-  _4361st Air Defence BN  (**attached** to 431st Motorized Brigade)_
-  _4362nd Air Defence BN  (**attached** to 432nd Motorized Brigade)_
-  _4363rd Air Defence BN  (**attached** to 433rd Motorized Brigade)_
- 4364th SA-8 BN
- 4365th SA-15 BN

**Comment by IAFAssafB** [comment]
I think the majority of it would stick in/around Damascus to defend the leaders. Its subordinate divisions would probably only maneuver as needed to meet an invading enemy army force but I don't think they would be defined as reinforcements/strategic reserves.

**Comment by 132ndNeck** [comment]
> 
> 
> I think the majority of it would stick in/around Damascus to defend the leaders. Its subordinate divisions would probably only maneuver as needed to meet an invading enemy army force but I don't think they would be defined as reinforcements/strategic reserves.

Not 100% sure what you mean,  but I assume you refer to 4th Corps? In that case I agree. They will be assigned to rear-area duties.

**Comment by IAFAssafB** [comment]
> > I think the majority of it would stick in/around Damascus to defend the leaders. Its subordinate divisions would probably only maneuver as needed to meet an invading enemy army force but I don't think they would be defined as reinforcements/strategic reserves.
> 
> Not 100% sure what you mean, but I assume you refer to 4th Corps? In that case I agree. They will be assigned to rear-area duties.

Yep. 4th Corps.

**Comment by 132ndNeck** [comment]
# 5th Corps

## 50th Armored Division (T-72)
**501th Armor Brigade**
- 5011 Armor BN
- 5012 Armor BN
- 5013 Armor BN
- 5014 Artillery BN
- 5061st Air Defence BN  (from 506th Air Defence Regiment)

**502nd Armor Brigade**
- 5021 Armor BN
- 5022 Armor BN
- 5023 Armor BN
- 5024 Artillery BN
- 5062nd Air Defence BN  (from 506th Air Defence Regiment)

**503rd Armor Brigade**
- 5031 Armor BN
- 5032 Armor BN
- 5033 Armor BN
- 5034 Artillery BN
- 5063rd Air Defence BN  (from 506th Air Defence Regiment)

**504th Logistics battalion**

**505th Rocket Artillery Battalion**

**551st Recon BN (From 55th Recon Regiment)**

**506th Air Defence Regiment**
-  _5061st Air Defence BN  (**attached** to 501st Armored Brigade)_
- _5062nd Air Defence BN (**attached** to 502nd Armored Brigade)_
- _5063rd Air Defence BN (**attached** to 503rd Armored Brigade)_
- 5064th SA-8 BN
- 5065th SA-15 BN




## 51st Armor Division (T-72)
**511th Armor Brigade**
- 5111th Armor BN
- 5112th Armor BN
- 5113th Armor BN
- 5114th Armor BN
- 5161st Air Defence BN  (from 516th Air Defence Regiment)

**512th Armor Brigade**
- 5121st Armor BN
- 5122nd Armor BN
- 5123rd Armor BN
- 5124th Artillery BN
- 5162nd Air Defence BN  (from 516th Air Defence Regiment)

**513th Armor Brigade**
- 5131st Armor BN
- 5132nd ArmorBN
- 5133rd Armor BN
- 5134th Artillery BN
- 5163nd Air Defence BN  (from 516th Air Defence Regiment)

**514th Logistics battalion**

**515th Rocket Artillery Battalion**

- 552nd Recon BN (attached to 51th Armor Division)

**516th Air Defence Regiment**
-  _5161st Air Defence BN  (**attached** to 511st Armor Brigade)_
-  _5162nd Air Defence BN  (**attached** to 512th Armor Brigade)_
-  _5163rd Air Defence BN  (**attached** to 513th Armor Brigade)_
- 5164th SA-8 BN
- 5165th SA-15 BN




## 52th Mechanized Brigade (BMP-2)
**521st Mechanized Brigade**
- 5211th Mechanized BN
- 5212th Mechanized BN
- 5213th Mechanized BN
- 5214th Artillery BN
- 5261st Air Defence BN  (from 526th Air Defence Regiment)

**522nd MechanizedBrigade**
- 5221st Mechanized BN
- 5222nd Mechanized BN
- 5223rd Mechanized BN
- 5224th Artillery BN
- 5262st Air Defence BN  (from 526th Air Defence Regiment)

**523nd Mechanized Brigade**
- 5231st Mechanized BN
- 5232nd Mechanized BN
- 5233rd Mechanized BN
- 5234th Artillery BN
- 5263st Air Defence BN  (from 526th Air Defence Regiment)

**524th Logistics battalion**

**525th Rocket Artillery Battalion**

- 553rd Recon BN (attached to 12th Mechanized Division)

**526th Air Defence Regiment**
- _5261st Air Defence BN  (**attached** to 521st Mechanized Brigade)_
- _5262nd Air Defence BN  (**attached** to 522th MechanizedBrigade)_
- _5263rd Air Defence BN  (**attached** to 523rd Mechanized Brigade)_
- 5264th SA-8 BN
- 5265th SA-15 BN




## 53th Air Defense Division
- _506th Air Defence Regiment (**Attached** to 50th Armored Division)_
-  _516th Air Defence Regiment (**Attached** to 51th Armored Division)_
-  _526th Air Defence Regiment (**Attached** to 52th Mechanized Division)_
- 531st SA-6 BN
- 532nd SA-11 BN
- 533rd HQ BN




## 54th Rocket artillery regiment
- 541st Heavy Rocket Artillery BN
- 542nd Heavy Rocket Artillery BN




## 55th Reconnaissance Regiment
- _551st Recon BN (**attached** to 50th Armored Division)_
- _552nd Recon BN (**attached** to 51th Armored Division)_
- _553rd Recon BN (**attached** to 52th Mechanized Division)_
- 554th Long Range Recon BN
- 556th Special Recon BN




## 56th Helicopter Regiment
- 561st AHS (Attack Helicopter Squadron) - MI-24
- 562nd THS (Transport Helicopter Squadron - MI-26
- 563rd THS - MI-26




## 57th Logistics Regiment
- 571st FARP BN
- 572nd Medical BN
- 573rd Logistics BN
- 574th Logistics BN
- 575th Logistics BN
