### ISSUE TITLE
Campaign organization - Roles and functions

### ISSUE THREAD

**Issue by 132ndNeck** [132nd-vWing/OPAR#9]
This thread is for discussing and agreeing on the campaign organization / roles / functions:

All positions should be volunteer, and if no one steps up, then it will be filled by us as the mission designers.

**Combined Joint Task Force HQ:**
- Sets the objectives for each event (or time period)
- Can change objectives if needed
- Sets allocation of missions (percent to each mission type)
- Uses input from VIS

<br>
<br>

**Virtual Intelligence Service (VIS):**
- Intelligence Air: Air Forces / SAMs and IADS
- Intelligence Ground: Ground forces
- Support decisionmaking fro CJTF HQ  ( Most Dangerous and Most Likely enemy course of action)
- Support all pilots planning and mission execution with updated intel prior to events
- Uses pilots BDA and reports after mission to compile a best possible enemy situation
- Manages target list and high value target list  
- Responsible for targeting (?, or should this be to CJTF HQ?)

<br>
<br>

**Air Operations Centre (AOC):**
- Mission designers, with insight in the .miz file (only persons with access and insight into .miz)
- Translates high level taskings from CJTF HQ to executable taskings / hosting specific events

<br>
<br>

**Admin**
- Mission designers provide inputs as necessary to both VIS (intelligence reports from higher) and to CJTF HQ (orders from Higher headquarter)

**Comment by IAFAssafB** [comment]
Regarding VIS:
1)  I suppose he would also get "tips" from ADMIN in the form of dispatches/reports ("CIA reporting a convoy passed Iraq/Syria border, composition xxxx time yyyy " etc?)
2) I suggest that when we make this public we state up front that this function can potentially be very busy better be done with a team rather than a single person (i.e someone focuses on "small level" analysis/evaluation (what a specific enemy BN or squadron is likely to do next) while other/s handling the high-level (large movements of forces combined with strategic situation etc)
3) I also suppose we should be providing all imagery files and static target information to the VIS and he would provide it to the pilots.

**Comment by 132ndNeck** [comment]
1. Yes, VIS will recive intel from higher/other sources (by us as mission designers as we see fit)
2. Yes, I agree. Best would be to get 2-4 persons, and some focus on the air situation and some on the ground situation. But we will see what we get, and take it from there. 
3. A combination. Hopefully VIS can also generate targets (after som injects from us). For example a IADS Command center, or ammunition depot, etc.  As long as VIS can understand why a target is important and its function, then they may suggest it to be striked to the CJTF HQ. And they will provide intel they have, and can request assets to provide intel about the target aswell.

We should of course have a hidden list, with various targets and the effect it may have if they are taken out, and then drop som intel now and then to see if they pick it up (for example, logistical convoys driving into a ammo site during a AR mission or strike mission. So the pilots potientially could pick it up, etc)

**Comment by 132ndNeck** [comment]
## CJTF HQ tasks:

**Allocation**
CJTF HQ will set allocation between the following: 
- DCA  - Defensive Counter Air: Defending against enemy air assets (aircraft)
- OCA - Offensive Counter Air: Attack against the enemy air assets (airfields, aircrafts, IADS, fuel, munitions, etc)
- CAS - Direct support to the friendly forces
- AR - Armed Recon. 
- AI - Air Interdiction: Attack against enemy ground targets
- Strategic attack (STRIKE): Attack against targets of strategic impact (War production, Command and Control etc)

So if they set 100% to CAS/AI, then there is no one availeble in case the enemy launches a air attack, and thus the friendly assets can be engaged.  Also if they set 100 % to OCA , then no support is given to the ground forces, and they ground forces will suffer.So they will need to find a good balance, and then the AOC translates this into taskings in the ATO.

**JPTL - Joint Prioritized Target List**
CJTF HQ will also select the targets for JPTL for this ATO. This is targets intended to be struck. So it can not be too many targets. JPTL targets are selcted based on the master target list which contains all targets. CJTF HQ will be supported by VIS for this, as VIS can help nominate or suggest targets to JPTL.
The JPTL will change daily (follow the ATO cycle)


## Inputs to CJTF HQ:
- VIS intelligence reports
- Situational reports from ground forces (provided by mission designers as required)

**Comment by 132ndNeck** [comment]
One suggestion :
We change the role of CJTF HQ to Joint Force Air Component Commander (JFACC), The we as mission designers assume the role of the overall CJTF HQ, and thus can give the overall direction (giving us more control, since that will be controlling also sea and ground forces), and the volunteers can affect the air campaign , thus not needed to focus too much on the things they not "care about" in the same way.

We can then submit several air requests from the ground force, and then have them decide who will be supported or not, and also the allocation as mentioned above. Then VIS can submit some targets for the JPTL for winning the war, and JFACC can submit some targets for winning the air campaign, and then we control the JPTL (targets that are to be attacked for the next ATO) better.

What do you think?


Then the JFACC (Joint Force Air Component Commander, commander of the air forces) can give out a Air Operations Directive to the AOC (us). This is all based on : https://www.jcs.mil/Portals/36/Documents/Doctrine/pubs/jp3_30.pdf

The AOD follows the following format: (Can be made into a simple word and/or google docs format to make it easy to fill out. The Situation will be given by us, enemy situation by VIS. What is important is really only part 3, the execution.

1.  SITUATION 
a.  JFC guidance (verbatim). 
(1)  JFC’s intent statement. 
(2)  Execution guidance (if issued). 
(3)  Supported and supporting command relationships. 
b.  Enemy situation. 
c.  Friendly situation (by joint force component). 
<br>
<br>
2.  MISSION The JFACC’s mission statement (verbatim).  Covers all phases of the operation, but AOD may state which phase this AOD applies to.  This should not change unless the mission itself changes. 
<br>
<br>

3.  EXECUTION–AIR OPERATIONS 
a.  JFACC’s intent. 
(1)  Purpose. 
(2)  End state. 
b.  Execution: What to do, when. 
c.  Focus of effort by objective. 
d.  Weight of effort by objective. 
e.  Acceptable level of risk. 
f.  Collateral damage and civilian casualty guidance
g.  TST guidance. 
h.  Other issues (e.g., ISR, information, space, mobility, focus of effort, PR). 

<br>
<br>
4.  ADMINISTRATION AND LOGISTICS 
Logistics considerations affecting operations during the AOD period. 
<br>
<br>
5.  COMMAND AND CONTROL C2 considerations affecting operations during the AOD period.  If there are no unique considerations, refer the reader to the JAOP commander relationship annex. 
<br>
<br>
6.  ANNEXES Use as required.  
Typical annexes: 
a.  Full listing of end state conditions, objectives, effects, and tasks, including MOP and effectiveness for each (as applicable). 
b.  Commander’s  critical  information  requirements  and  essential  elements  of information applicable for the AOD period.

**Comment by IAFAssafB** [comment]
So many new acronyms for me , I'll need some time learning it :-)
So to see if I get this right:
1) We take CJTF-HQ role, and AOC
2) Volunteers are taking VIS, AOD and JAFCC
3) We as CJTF-HQ are "knowing" the overall intelligence picture and can "steer" the whole war effort the way we see fit.
4) We stream the intelligence to the VIS
5) We instruct the JAFCC what efforts are planned during the next day of war ("A. Israel is going to initiate an offensive to retake Mt. Hermon; B. Turkey will be defending on the border against a Syrian division near XXX; C. We've been authorized to conduct a deep strike against Syrian logistics center EAST of DAMASCUS; D. ...." 
6) JAFCC takes the objectives we've outlined, consults with his VIS and decide which objectives will be supported by the wing during the event.
7) JAFCC issues an AOD to AOC (Us).
8) AOC (Us) builds the ATO based on the AOD and share it with all pilots so they can start choosing what role they wish to take, and form up flights and packages)
9) VIS is fetching specific intelligence bits from CJTF-HQ and distributes it to the pilots/ JAFCC to enable detailed planning.

Did I get this flow right?
Once I've wrapped my head around it I'll try to do a graphical representation of it so it might make it easier on everyone (including timeline of when each step should take place)

**Comment by 132ndNeck** [comment]
Almost right, let me sum up the suggestion, and see if it makes sense for you aswell:

We have the following "agencies"/roles:
- CJTF HQ (Commander of the entire task force, including air, ground and sea forces)
- JFACC (Commander of all the air forces. In addition there are the commanders for ground and sea forces, but not relevant for uss)
- AOC: Air Operations Centre. Translating guidance from JFACC to an executable ATO
- VIS: Virtual Intelligence Service: Intelligence agency supporting JFACC, AOC and pilots/JTACs

Volunteers take VIS and JFACC.

Flow:
1. CJTF HQ provides intention, and objectives and priorities for the Joint Force (ground, sea, air) (big picture, and will not change from day to day, but maybe every other day, or after several days.
Joint Prioritized Target List is published from the CJTF HQ. This is targets that are to be targeted the next ATO period. JFACC can nominate 1-4 targets to this list. In addition VIS can nominate 1-4 targets for this list, but the final decision will be from CJTF HQ (me and you). We will also inject the targets requested from the ground force and the naval force.
2. JFACC takes the guidance from CJTF HQ  +the JPTL and inputs from VIS and produces a AOD (Air Operations Directive). 
In addition to these inputs, we will provide request for support from the ground force and naval force to the JFACC. This so the JFACC will need to prioritize between the request and decide who to support.
The JFACC will with the AOD do the allocation as mentioned in a comment above (giving the % of air sorties to DCA, OCA, CAS, AI, STRIKE). In this process JFACC also nominates the targets for the next event (not the one beeing planned, but the next)
3. The AOD goes to AOC (me and you), who will produce a executable ATO, with taskings and priorites based on the AOD
4. We assign pilots to the taskings as normal
5. Pilots conducts planning and execution of the mission. AWACS controller have command and control during execution, based on all products (ATO, JPTL, AOD)
6. After mission, all pilots and controllers provide BDA and AARs.
7. VIS produces a INTSUM based on the event, and the process continues
8. CJTF HQ provides a new  JPTL (a new JPTL for each event) and revises and updates guidance if there is any changes. The JPTL is the  based on the inputs in step 2.

Does that make sense? And does it seem reasonable and interesting?  And doable?

**Comment by IAFAssafB** [comment]
Makes total sense. Thanks for the clarification. I've never went into those details of how things are conducted (IDF doesn't play the same way as US / NATO I suppose :-P )
And it adds a lot of immersion to the whole campaign I think. Very good addition!

**Comment by 132ndNeck** [comment]
Excellent! Then we can move forward with that organization, and iron out the details needed, and the various products and formats, so everything is ready.

I was also thinking to have different Discord channels:

So a seperate OPAR section with the following channels (all on the 132nd server)  (several channels, but just to streamline the information if things go in the right channels)
- **Event flight planning** (Next event) - Coordination for everyone involved
- **JFACC channel:** For JFACC personel, to discuss and work toward the AOD they are to publish
- **VIS channel:** For VIS personell to discuss and collabarate between VIS to generate intelligence products
- **Reports/Orders**: Channel where reports and orders can arrive during a mission (For AWACS to handle during events). Can also be used for notification when we provide orders/Report as injects (but they should also be availeble on the briefing website
- **BDA reporting channel** : For all involved. To provide BDAs and reports after events.
- **RFI channel:** Request for information. For everyone involved. Everyone can Request information from CJTF HQ / VIS.
- **Targeting channel:** For VIS and JFACC + CJTF HQ and AOC to discuss targeting and targeting strategies and nominations of targets to the JPTL.

**Comment by IAFAssafB** [comment]
Yep!
As for the "Reports/Orders" I think it should be an announcements-only channel where we only put notes/details/reports but those shall be processed/discussed in any of the other channels.

**Comment by 132ndNeck** [comment]
> 
> 
> Yep!
> As for the "Reports/Orders" I think it should be an announcements-only channel where we only put notes/details/reports but those shall be processed/discussed in any of the other channels.

Yes, I agree.

**Comment by 132ndNeck** [comment]
Ok, so for products that will be used in the campaign:

- **JPTL (Joint Prioritized Target List):** From CJTF HQ to JFACC and AOC. Contains the prioritized targets for the coming ATO. The JPTL also contains the TST Matrix, which consist of the high priority targets that takes precedence over everything else (if applicable). There does not need to be any target on the TST matrix. The JTPL and TST matrix will be based on inputs from JFACC and VIS (which both will nominate targets they think is important for them to do their mission). In addition will we as mission designers add targets in behalf of the land component and the naval component.
- **INTSUM (Intelligence Summary):** Created by VIS after a event. Will be the basis for planning and preperation for the next event. Aid for CJTF HQ to updated guidance and intentions or mission. It also aids JFACC when they are to produce the AOD, and will also help pilots in their planning/preperation for the mission.
- **AOD (Air Operations Directive):** The guidance from the commander of  the Air Forces (Joint Force Air Component Command, JFACC) to the air forces involved in the operation. The AOD is described in a few posts above, and provides together with the JPTL the guidance needed for the AOC (Mission designers/event hosts) to create taskings. The AOD and JPTL also gives guidance  for AWACS during the execution of the  mission. Initially this will be somewhat more workintensive, as they will need to figure out a campaignplan for the aircampaign on how to achieve air superiority and set conditions for the Air Interdiction campaign and Strike campaign within Syria to actually win the war and make the Syrian regime give up.
- **Air Requests:** From Land component (ground forces) and naval forces (provided by us as mission designers, playing the role as LCC and MCC, Land Component Commander and Maritime Component Commander). We will use the standard Air Request form that the JTACs use. This way we can steer activity where we want it (few requests), or give flexibility (many requests, more than they have assets to). We will also make sure to add a point in the AOD which contains information about which requests are supported.
- **Orders:** From CJTF HQ to the component commanders (LCC, MCC and JFACC). To give guidance on what to do. Should be short and simple. (So basicly from us as mission designers to the JFACC)
- **INTREP (Intelligence Report):** From us as mission designers/event hosts to VIS when we need to inject some information. As much as possible should be injected before the production of the INTSUM, so it is included in the INTSUM before the event.  These INTREPs can be short with critical information, or longer reports explaining stuff we need to convey (for example about the Syrian Chemical Weapon program, giving indicators for where they can find sites, etc).
- **Target folders:** Target folders with detailed information needed for the excution of missions, when needed. Can be very simplified, as long as it gives enough to the pilots for planning. Can be produced either from us as hosts, or hopefully also some to be generated by VIS during the campaign.


Anything else you can think of that we need of products during the campaign?  (of course not a problem to add more as we see fit).
